// <auto-generated />
using System;
using FundacionAMA.Infrastructure.Persistence.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FundacionAMA.Infrastructure.Migrations
{
    [DbContext(typeof(FundacionAMADbContext))]
    [Migration("20240722124631_202407220746001")]
    partial class _202407220746001
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FundacionAMA.Domain.Entities.Grupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_Grupo_ID");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("grupo");
                });

            modelBuilder.Entity("FundacionAMA.Domain.Entities.GrupoCliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int>("Cliente_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int?>("GrupoId1")
                        .HasColumnType("int");

                    b.Property<int>("Grupo_Id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("GrupoId1");

                    b.ToTable("grupoCliente");
                });

            modelBuilder.Entity("FundacionAMA.Domain.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Apellido")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_Person_ID");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("person");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Person");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("FundacionAMA.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Clave")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.Property<int>("Persona_Id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Usuario")
                        .HasColumnType("longtext");

                    b.HasKey("Id")
                        .HasName("PK_User_ID");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("Persona_Id");

                    b.ToTable("user");
                });

            modelBuilder.Entity("FundacionAMA.Domain.Entities.Cliente", b =>
                {
                    b.HasBaseType("FundacionAMA.Domain.Entities.Person");

                    b.Property<string>("Codigo")
                        .HasColumnType("longtext");

                    b.Property<string>("PrimeraCompra")
                        .HasColumnType("longtext");

                    b.HasDiscriminator().HasValue("Cliente");
                });

            modelBuilder.Entity("FundacionAMA.Domain.Entities.GrupoCliente", b =>
                {
                    b.HasOne("FundacionAMA.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.HasOne("FundacionAMA.Domain.Entities.Grupo", "Grupo")
                        .WithMany()
                        .HasForeignKey("GrupoId1");

                    b.Navigation("Cliente");

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("FundacionAMA.Domain.Entities.User", b =>
                {
                    b.HasOne("FundacionAMA.Domain.Entities.Person", "Persona")
                        .WithMany()
                        .HasForeignKey("Persona_Id")
                        .HasConstraintName("Fk_Persona_Id");

                    b.Navigation("Persona");
                });
#pragma warning restore 612, 618
        }
    }
}
