// <auto-generated> This file has been auto generated by StringCGE GeneradorCSharp. </auto-generated>
#nullable disable
using FundacionAMA.Domain.Shared.Entities;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

using System;
using System.Collections.Generic;

namespace FundacionAMA.Domain.Entities;

public partial class Cliente: Person
{
    /// <summary>
    /// Codigo
    /// </summary>
    public string Codigo  { get; set; }
    /// <summary>
    /// PrimeraCompra
    /// </summary>
    public string PrimeraCompra  { get; set; }
    /// <summary>
    /// Grupos
    /// </summary>
    public List<GrupoCliente>? Grupos  { get; set; }

}