// <auto-generated> This file has been auto generated by StringCGE GeneradorCSharp. </auto-generated>
#nullable disable
using FundacionAMA.Domain.Shared.Entities;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

using System;
using System.Collections.Generic;

namespace FundacionAMA.Domain.Entities;

public partial class GrupoCliente: BaseEntity<int>
{
     /// <summary>
    /// Grupo_Id
    /// </summary>
    public int Grupo_Id { get; set; }
    /// <summary>
    /// Grupo
    /// </summary>
    public Grupo? Grupo  { get; set; }
     /// <summary>
    /// Cliente_Id
    /// </summary>
    public int Cliente_Id { get; set; }
    /// <summary>
    /// Cliente
    /// </summary>
    public Cliente? Cliente  { get; set; }

}