// <auto-generated> This file has been auto generated by StringCGE GeneradorCSharp. </auto-generated>
#nullable disable
using FundacionAMA.Domain.Shared.Entities;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

using System;
using System.Collections.Generic;

namespace FundacionAMA.Domain.Entities;

public partial class Grupo: BaseEntity<int>
{
    /// <summary>
    /// Nombre
    /// </summary>
    public string Nombre  { get; set; }
    /// <summary>
    /// Clientes
    /// </summary>
    public List<GrupoCliente>? Clientes  { get; set; }

}