// <auto-generated> This file has been auto generated by StringCGE GeneradorCSharp. </auto-generated>
#nullable disable
using FundacionAMA.Domain.Shared.Entities;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

using System;
using System.Collections.Generic;

namespace FundacionAMA.Domain.Entities;

public partial class Person: BaseEntity<int>
{
    /// <summary>
    /// Nombre
    /// </summary>
    public string Nombre  { get; set; }
    /// <summary>
    /// Apellido
    /// </summary>
    public string Apellido  { get; set; }
    /// <summary>
    /// Edad
    /// </summary>
    public int Edad  { get; set; }

}