// <auto-generated> This file has been auto generated by StringCGE GeneradorCSharp. </auto-generated>
#nullable disable
using FundacionAMA.Domain.Shared.Entities;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

using System;
using System.Collections.Generic;

namespace FundacionAMA.Domain.Entities;

public partial class User: BaseEntity<int>
{
    /// <summary>
    /// Usuario
    /// </summary>
    public string Usuario  { get; set; }
    /// <summary>
    /// Clave
    /// </summary>
    public string Clave  { get; set; }
     /// <summary>
    /// Persona_Id
    /// </summary>
    public int Persona_Id { get; set; }
    /// <summary>
    /// Persona
    /// </summary>
    public Person? Persona  { get; set; }
    /// <summary>
    /// Nombre
    /// </summary>
    public string Nombre  { get; set; }

}