// <auto-generated> This file has been auto generated by EF StringCGE Genera_CSharp. </auto-generated>
using FundacionAMA.Domain.Entities;
using FundacionAMA.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace FundacionAMA.Infrastructure.Persistence.Configurations
{
    public partial class ClienteConfiguration : IEntityTypeConfiguration<Cliente>
    {
        public void Configure(EntityTypeBuilder<Cliente> entity)
        {

            //No se configura esto ya que su PK esta en alguna super clase
            //entity.HasKey(e => e.Id).HasName("PK_Cliente_ID");
            //entity.HasIndex(e => e.Id).IsUnique();

            entity
                .HasMany(c => c.Grupos)
                .WithOne()
                .IsRequired(false)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.Ignore(c => c.Grupos);

            
            OnConfigurePartial(entity);
        }
        partial void OnConfigurePartial(EntityTypeBuilder<Cliente> entity);
    }
}
