// <auto-generated> This file has been auto generated by EF StringCGE Genera_CSharp. </auto-generated>
using FundacionAMA.Domain.Entities;
using FundacionAMA.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace FundacionAMA.Infrastructure.Persistence.Configurations
{
    public partial class GrupoClienteConfiguration : IEntityTypeConfiguration<GrupoCliente>
    {
        public void Configure(EntityTypeBuilder<GrupoCliente> entity)
        {

            entity.HasKey(e => e.Id).HasName("PK_GrupoCliente_ID");
            entity.HasIndex(e => e.Id).IsUnique();

            entity
            .HasOne(u => u.Grupo)
            .WithMany()
            .HasForeignKey(u => u.Grupo_Id)
            .HasConstraintName("Fk_Grupo_Id")
            .IsRequired(false)
            .OnDelete(DeleteBehavior.ClientSetNull);
            //entity.Property(e => e.Grupo).IsRequired();
            entity
            .HasOne(u => u.Cliente)
            .WithMany()
            .HasForeignKey(u => u.Cliente_Id)
            .HasConstraintName("Fk_Cliente_Id")
            .IsRequired(false)
            .OnDelete(DeleteBehavior.ClientSetNull);
            //entity.Property(e => e.Cliente).IsRequired();

            
            OnConfigurePartial(entity);
        }
        partial void OnConfigurePartial(EntityTypeBuilder<GrupoCliente> entity);
    }
}
