// <auto-generated> This file has been auto generated by EF StringCGE Genera_CSharp. </auto-generated>
using FundacionAMA.Domain.Entities;
using FundacionAMA.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace FundacionAMA.Infrastructure.Persistence.Configurations
{
    public partial class GrupoConfiguration : IEntityTypeConfiguration<Grupo>
    {
        public void Configure(EntityTypeBuilder<Grupo> entity)
        {

            entity.HasKey(e => e.Id).HasName("PK_Grupo_ID");
            entity.HasIndex(e => e.Id).IsUnique();

            entity
                .HasMany(c => c.Clientes)
                .WithOne()
                .IsRequired(false)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.Ignore(c => c.Clientes);

            
            OnConfigurePartial(entity);
        }
        partial void OnConfigurePartial(EntityTypeBuilder<Grupo> entity);
    }
}
