// <auto-generated> This file has been auto generated by EF StringCGE Genera_CSharp. </auto-generated>
using FundacionAMA.Domain.Entities;
using FundacionAMA.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace FundacionAMA.Infrastructure.Persistence.Configurations
{
    public partial class PersonConfiguration : IEntityTypeConfiguration<Person>
    {
        public void Configure(EntityTypeBuilder<Person> entity)
        {

            entity.HasKey(e => e.Id).HasName("PK_Person_ID");
            entity.HasIndex(e => e.Id).IsUnique();


            
            OnConfigurePartial(entity);
        }
        partial void OnConfigurePartial(EntityTypeBuilder<Person> entity);
    }
}
