// <auto-generated> This file has been auto generated by EF StringCGE Genera_CSharp. </auto-generated>
using FundacionAMA.Domain.Entities;
using FundacionAMA.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace FundacionAMA.Infrastructure.Persistence.Configurations
{
    public partial class UserConfiguration : IEntityTypeConfiguration<User>
    {
        public void Configure(EntityTypeBuilder<User> entity)
        {

            entity.HasKey(e => e.Id).HasName("PK_User_ID");
            entity.HasIndex(e => e.Id).IsUnique();

            entity
            .HasOne(u => u.Persona)
            .WithMany()
            .HasForeignKey(u => u.Persona_Id)
            .HasConstraintName("Fk_Persona_Id")
            .IsRequired(false)
            .OnDelete(DeleteBehavior.ClientSetNull);
            //entity.Property(e => e.Persona).IsRequired();

            
            OnConfigurePartial(entity);
        }
        partial void OnConfigurePartial(EntityTypeBuilder<User> entity);
    }
}
